### ISSUE TITLE
Where is the `lifo` strategy?

### ISSUE THREAD

**Issue by manuel-rubio** [devinus/poolboy#143]
I was checking an old version where I could see:

```erlang
        {empty, Empty} ->
            Workers = case Strategy of
                lifo -> [Pid | State#state.workers];
                fifo -> State#state.workers ++ [Pid]
            end,
            State#state{workers = Workers, waiting = Empty, overflow = 0}
```

But this was completely removed in a new version and now it's not possible to use `lifo` strategy, why?

https://github.com/devinus/poolboy/blob/9212a8770edb149ee7ca0bca353855e215f7cba5/src/poolboy.erl#L344L346

**Comment by zugolosian** [comment]
Lifo is still there, because it's a queue now the ordering of returning workers to the queue is no longer important. You're able to get the most recently returned worker or the oldest one using the strategy for selecting the worker rather than how you return them. Lifo is also the default strategy if you don't pass one in

**Comment by manuel-rubio** [comment]
I missed this code, thanks!
https://github.com/devinus/poolboy/blob/9212a8770edb149ee7ca0bca353855e215f7cba5/src/poolboy.erl#L309L312
